### ISSUE TITLE
bluescreen at 0x7323901 error not found

### ISSUE THREAD

**Issue by eele94** [EdenCox/Kruispunt-Simulatie#1]
I ran the simulation at my laptop, I got a bluescreen and now my laptop died.
Do you know any fix???

Help plzz

**Comment by nielslanting** [comment]
Create a PR please, you can use the following check list.

**Todos:**
- [ ]  Write tests
- [ ]  Fix linting errors
- [ ]  Make sure code coverage hasn't dropped
- [ ]  Provide verification config/commands/resources
- [ ]  Change ready for review message below

**Comment by eele94** [comment]
Thanks! I have tried those things and now I get this:
![](https://i.ytimg.com/vi/OPWZw48US2w/maxresdefault.jpg)
